title: Just Fox Docs
description: Fox Documentation and guide
theme: just-the-docs

color_scheme: dark

url: https://walakj.github.io/just_my_docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
